repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        language: system
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/kamadorueda/alejandra
    rev: 4.0.0
    hooks:
      - id: alejandra
        language: system
  - repo: https://github.com/fidgetingbits/pre-commit-statix
    rev: v1.0.0
    hooks:
      - id: statix-check
